version: "3.8"

services:

    node-api:
        build: 
            context: .
            dockerfile: Dockerfile

        image: node:latest

        container_name: node-api

        command: npm run dev
        
        environment: 
            PORT: 3333
            BCRYPT_SALT: 30

        ports: 
            - "9000:3333"

        volumes: 
            - ".:/usr/app"

        restart: always
